name: dart_api_service
description: A starting point for Dart libraries or applications.
version: 1.1.3
repository: https://github.com/Iconica-Development/dart_api_service

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ^3.3.3

dependencies:
  http: ^1.2.1
  meta: ">=0.0.1 <2.0.0"

dev_dependencies:
  test: ^1.24.0
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^7.0.0
  mocktail: ^1.0.3
