name: dart_api_service
description: A starting point for Dart libraries or applications.
version: 1.1.1
repository: https://github.com/Iconica-Development/dart_api_service

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  meta: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
  mocktail: ^1.0.3
